item { 
	name:'Adidas'
	id:1
}
item { 
	name:'Apple'
	id:2
}
item { 
	name:'BMW'
	id:3
}
item { 
	name:'Citroen'
	id:4
}
item { 
	name:'Cocacola'
	id:5
}
item { 
	name:'DHL'
	id:6
}
item { 
	name:'Fedex'
	id:7
}
item { 
	name:'Ferrari'
	id:8
}
item { 
	name:'Ford'
	id:9
}
item { 
	name:'Google'
	id:10
}
item { 
	name:'Heineken'
	id:11
}
item { 
	name:'HP'
	id:12
}
item { 
	name:'Intel'
	id:13
}
item { 
	name:'McDonald'
	id:14
}
item { 
	name:'Mini Cooper'
	id:15
}
item { 
	name:'Nbc'
	id:16
}
item { 
	name:'Nike'
	id:17
}
item { 
	name:'Pepsi'
	id:18
}
item { 
	name:'Porsche'
	id:19
}
item { 
	name:'Puma'
	id:20
}
item { 
	name:'RedBull'
	id:21
}
item { 
	name:'Sprite'
	id:22
}
item { 
	name:'Starbucks'
	id:23
}
item { 
	name:'Texaco'
	id:24
}
item { 
	name:'Unicef'
	id:25
}
item { 
	name:'Vodafone'
	id:26
}
item { 
	name:'Yahoo'
	id:27
}
